"""8

Revision ID: 1c1e5b290c7e
Revises: b60a88bf74fc
Create Date: 2025-07-14 11:30:27.191842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1e5b290c7e'
down_revision = 'b60a88bf74fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
