"""1

Revision ID: b60a88bf74fc
Revises: 
Create Date: 2025-07-14 11:05:52.659638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60a88bf74fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id_emp', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_emp')
    )
    op.create_table('applications',
    sa.Column('id_app', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id_emp'], ),
    sa.PrimaryKeyConstraint('id_app')
    )
    op.create_table('users',
    sa.Column('id_user', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('recover', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id_emp'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('models',
    sa.Column('id_model', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('documentacion', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id_app'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id_emp'], ),
    sa.PrimaryKeyConstraint('id_model')
    )
    op.create_table('conections',
    sa.Column('id_conn', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id_app'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id_emp'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id_model'], ),
    sa.PrimaryKeyConstraint('id_conn')
    )
    op.create_table('queries',
    sa.Column('id_query', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('res_SQL', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id_model'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_query')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    op.drop_table('conections')
    op.drop_table('models')
    op.drop_table('users')
    op.drop_table('applications')
    op.drop_table('companies')
    # ### end Alembic commands ###
