"""11

Revision ID: b6617c9e7d95
Revises: 1c1e5b290c7e
Create Date: 2025-07-14 12:37:00.685965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6617c9e7d95'
down_revision = '1c1e5b290c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_application',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id_app'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id_emp'], ),
    sa.PrimaryKeyConstraint('company_id', 'application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_application')
    # ### end Alembic commands ###
