name: Deploy Vite to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        type: choice
        required: true
        default: deploy
        options:
          - main
          - deploy
        

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm i
        working-directory: proyectocziber

      - name: Build
        run: npm run build
        working-directory: proyectocziber

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: proyectocziber/dist
        

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
